language: node_js
node_js:
  "node"
cache:
  directories:
    "node_modules"
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  fqdn: b32.vecha.in
  on:
    branch: master
